events {
    worker_connections 1024;
}

stream {
    upstream account_service {
        server account-service-1:3002;
        server account-service-2:3002;
    }

    server {
        listen 80;
        proxy_pass account_service;
    }
}
