events {
    worker_connections 1024;
}

stream {
    upstream api_gateway {
        server api-gateway-1:3000;
        server api-gateway-2:3000;
        server api-gateway-3:3000;
    }

    server {
        listen 80;
        proxy_pass api_gateway;
    }
}