events {
    worker_connections 1024;
}

stream {
    upstream transfer_service {
        server transfer-service-1:3003;
        server transfer-service-2:3003;
    }

    server {
        listen 80;
        proxy_pass transfer_service;
    }
}
