events {
    worker_connections 1024;
}

stream {
    upstream user_service {
        server user-service:3001;
        server user-service-2:3001;
    }

    server {
        listen 80;
        proxy_pass user_service;
    }
}